name: CI (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DVC_REMOTE_NAME: gcs
      MODEL_PATH: artifacts/model.joblib
      METRICS_PATH: artifacts/metrics.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (project + DVC + CML)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install dvc dvc-gs pytest cml

      - name: Auth for GCS (DVC)
        run: |
          echo "$GCP_SA_KEY_BASE64" | base64 -d > "$RUNNER_TEMP/sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json" >> $GITHUB_ENV
        env:
          GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: DVC pull artifacts
        run: |
          dvc remote list
          dvc pull -r "$DVC_REMOTE_NAME" -v

      - name: Sanity check required files (fail fast if missing)
        run: |
          ls -lah artifacts || true
          test -f "$MODEL_PATH"
          test -f "$METRICS_PATH"

      - name: Run tests (optional)
        run: pytest -q || true

      - name: Prepare CI report (CML)
        run: |
          echo "CI report" > report.md
          echo "" >> report.md
          echo "**Branch:** $GITHUB_REF_NAME" >> report.md
          echo "" >> report.md
          echo "**metrics.json:**" >> report.md
          cat "$METRICS_PATH" >> report.md

      - name: Post PR comment (CML)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml comment create --pr --publish report.md

      - name: Upload report (push runs)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: ci-report
          path: report.md

